### ISSUE TITLE
mnist_simple.py can not reproduce the same figure.

### ISSUE THREAD

**Issue by muratkrty** [tehtechguy/mHTM#1]
Failed to reproduce the same figure (see below figure) while  running mnist_simple.py with same parameters from the paths /mHTM-master/dev/sp_math_pub/ and /mHTM-master/src/examples The installation procedure followed  from the [mHTM's README](https://github.com/tehtechguy/mHTM) and prequsits are succesfully installed.

![figure_1](https://cloud.githubusercontent.com/assets/1232093/24095305/c9f67a18-0d5c-11e7-9aba-9d9ca1a1109d.png)

While debugging the program, I realized that the sp.predict method outputs only a matrix which is populated only with zeros.  
`    sp_pred = sp.predict(inputs) `
`    print np.count_nonzero(sp_pred*1) # 0`

Any ideas to fade away this problem ?

**Comment by jmnatzaganian** [comment]
@muratkrty - I was unable to reproduce this issue. It is possible that this is a dependency issue. I have added a requirements.txt file. Please use it to install the packages matching those on my system.

If you are still having issues, try using a virtualenv. This will give you a clean Python install where you can install the required packages and this project.

**Comment by muratkrty** [comment]
Thanks for reply. 
I guess, there was a problem with version conflicts (scipy and scikit_learn). Using virtualenv with requirements.txt works.
 
![figure_2](https://cloud.githubusercontent.com/assets/1232093/24359443/adc96e1a-1304-11e7-9410-db3cc8eac15f.png)
